project/MainClient/urls.py
from django.urls import path
from graphene_django.views import GraphQLView
from django.contrib.auth import views as auth_views
from . import views
app_name='project'
urlpatterns=[ 
        
        path("wallet/<slug:slug>",views.WalletDetail.as_view(),name="wallet"),
        path('login', views.loginPage, name="loginPage"),
        path("home",views.HomeView.as_view(),name="home"),
        path('registration',views.registerPage,name='register.new'),
        path('itemupload',views.ItemsCreateView.as_view(),name="itemupload"),
        path('walletupdate/<slug:slug>',views.WalletUpdateView.as_view(),name="walletupdate"),
        path('customerprofile/<int:pk>/',views.CustomerProfileView.as_view(),name="customerprofile"),
        path('addressupdate/<slug:slug>',views.AddressesView.as_view(),name="addressupdate"),
        path('Items',views.ItemListView.as_view(),name='items'),
        path('Itemsdetail/<slug:slug>',views.ItemDetailView.as_view(),name='itemdetail'),
        path('add_to_cart/<slug:slug>',views.add_to_cart,name='add_to_cart'),
        path('thanks/', views.thanks, name='thanks'),
        path('cart',views.cart_view,name='cart'),
        path('remove_from_cart/<slug:slug>/', views.remove_from_cart, name='remove_from_cart'),
        path('create_order/', views.create_order, name='create_order'),
        path('logout',views.logout_view,name='logout'),
        path('previousorder',views.previous_orders_view,name='previousorder'),
        path('graphql', GraphQLView.as_view(graphiql=True)),
        path("checkout")
        


        
        
        
]

project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib import admin  
from django.conf import settings  
from django.conf.urls.static import static


from MainClient import views  


urlpatterns = [
    path('admin/', admin.site.urls),
    path('customerSide/',include('MainClient.urls',namespace='MainClient')),
    path('',views.welcome,name='welcome'),
    
    
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

project/MainClient/models.py
from django.db import models
from django.db.models.signals import post_save
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from django.dispatch import receiver
import random
import string
from django.urls import reverse

#utilities for instances

def Id_generator():
    Id=random.randint(0,999999999)
    converted_Id=str(Id)
    if CustomerProfile.objects.filter(customerId=converted_Id).exists()==False:
          
           return converted_Id
    else:
        return Id_generator()

def LoggedUser(request):
	currentUserid=request.user.id
	return currentUserid

def LoggedUserName(request):
	currentUserName=User.username
	return currentUserName


def slug_generator(size=10, chars=string.ascii_uppercase + string.digits + string.ascii_lowercase):
    slug=''.join(random.choice(chars) for _ in range(size))
    if Items.objects.filter(slug=slug).exists()==False:
          return slug
    else:
        return slug_generator()

class CustomerProfile(models.Model):
    user=models.OneToOneField(User, null=True,blank=True, on_delete=models.CASCADE)
    customerId=models.CharField(max_length=10 ,blank=True)   #Uniq Id

class Wallet(models.Model):
    user=models.OneToOneField(User,null=True, on_delete=models.CASCADE)
    name=models.CharField(max_length=100,blank=True,default=' ')
    balance=models.IntegerField(blank=True,default=0)
    slug=models.SlugField(max_length=100,blank=True)

    def __str__(self):
        return self.name
    def __int__(self):
        return self.user_id

class Items(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.TextField()
    image = models.ImageField()
    slug=models.SlugField(max_length=100,blank=True)

class CartItems(models.Model):
    user=models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    item = models.ForeignKey(Items, on_delete=models.CASCADE,null=True, default=None)
    quantity = models.IntegerField(default=1)
    ordered=models.BooleanField(default=False)

    def total_price(self):
        return self.quantity * self.item.price
    

class Orderss(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItems)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    
    
class Address(models.Model):
    user=models.OneToOneField(User, blank=True, on_delete=models.CASCADE)
    title=models.CharField(max_length=100)
    city=models.CharField(max_length=100)
    street=models.CharField(max_length=100)
    zipcode=models.CharField(max_length=5)
    apartment_no=models.CharField(max_length=25)
    daire=models.CharField(max_length=5)
    slug=models.SlugField(max_length=100, blank=True)



@receiver(post_save,sender=User)
def create_user_profile(instance, created, **kwargs):
    if created:
       CustomerProfile.objects.create(user=instance)
       Wallet.objects.create(user=instance)
       Address.objects.create(user=instance)
    
def pre_save_ID(sender,instance, *args, **kwargs ):
    if not instance.customerId:
        instance.customerId=Id_generator()
pre_save.connect(pre_save_ID,sender=CustomerProfile)

def pre_save_slug(sender,instance, *args, **kwargs):
    if not instance.slug:
        instance.slug=slug_generator()
pre_save.connect(pre_save_slug,sender=Items)
pre_save.connect(pre_save_slug,sender=Wallet)
pre_save.connect(pre_save_slug,sender=Address)



def pre_save_LoggedUser(sender,instance, *args, **kwargs ):
    if not instance.user:
        instance.user=LoggedUser
pre_save.connect(pre_save_LoggedUser,sender=CustomerProfile)
pre_save.connect(pre_save_LoggedUser,sender=Wallet)
pre_save.connect(pre_save_LoggedUser,sender=Address)





       


        
       

project/MainClient/forms.py
from .models import *
from django import forms
from django.forms import formset_factory

class AddToCartForm(forms.Form):
    slug = forms.CharField()
    quantity = forms.IntegerField(min_value=1)


AddToCartFormSet = formset_factory(AddToCartForm, extra=1)

project/MainClient/views.py
from datetime import timezone
from django.shortcuts import render
from django.views.generic import ListView,CreateView,TemplateView,UpdateView,DetailView
from .models import CustomerProfile, Items,Wallet, Address, CartItems,Orderss
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.template import loader
from django.urls import reverse
from django.http import HttpResponseRedirect
import graphene
from graphene_django.views import GraphQLView
from .models import CustomerProfile




def LoggedUserId(request):
		id=request.Wallet.get('id')
		return id
class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']


class WalletUpdateView(UpdateView):
	model=Wallet
	fields=["name","balance"]
	template_name="MainClient/walletform.html"
	def get_success_url(self):
		pk = self.object.pk
		return reverse('MainClient:customerprofile', kwargs={'pk': pk})
	

class WalletDetail(DetailView):
	template_name='MainClient/walletview.html'
	model=Wallet
	
class AddressesView(UpdateView):
	model =Address
	fields=['title','city',"street","zipcode","apartment_no","daire"]
	template_name="MainClient/AddressUpdate.html"
	success_url='customerSide/home'

def registerPage(request):
	if request.user.is_authenticated:
		return redirect('/customerSide/home')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('/customerSide/login')
			

		context = {'form':form}
		return render(request, 'MainClient/registerform.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect('/customerSide/home')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('/customerSide/home')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'MainClient/loginform.html', context)
		
     
class HomeView(TemplateView):
	template_name='MainClient/home.html'
	model=Address
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(HomeView, self).dispatch(*args, **kwargs)
	

class ItemsCreateView(CreateView):
	template_name='MainClient/itemupload.html'
	success_url='/itemupload'
	model=Items
	fields=['title','price','description','image']

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(ItemsCreateView, self).dispatch(*args, **kwargs)
	@method_decorator(user_passes_test(lambda u: u.is_superuser))
	def dispatch(self, *args, **kwargs):
		return super(ItemsCreateView, self).dispatch(*args, **kwargs)
	
class CustomerProfileView(DetailView):
	template_name='MainClient/customerprofile.html'
	model=CustomerProfile
	context_object_name = 'customer'

class ItemListView(ListView):
	model=Items
	paginate_by=10
	template_name='MainClient/itemlist.html'



class ItemDetailView(DetailView):
	model=Items
	template_name='MainClient/itemdetail.html'

def add_to_cart(request, slug):
    item = get_object_or_404(Items, slug=slug)
    cart_item, created = CartItems.objects.get_or_create(
        user=request.user,
        item=item,
        ordered=False
    )
    if not created:
        # update the quantity of the item
        cart_item.quantity += 1
        cart_item.save()
    return redirect('MainClient:items')

def remove_from_cart(request, slug):
    item = get_object_or_404(Items, slug=slug)
    cart_item = get_object_or_404(CartItems, user=request.user, item=item, ordered=False)
    if cart_item.quantity > 1:
        # reduce the quantity of the item
        cart_item.quantity -= 1
        cart_item.save()
    else:
        # delete the cart item
        cart_item.delete()
    return redirect('MainClient:cart')

def create_order(request):
    if request.user.is_authenticated:
        cart_items = CartItems.objects.filter(user=request.user, ordered=False)
        if cart_items.exists():
            # get the user's wallet and calculate the total price of the items in the cart
            wallet = Wallet.objects.get(user=request.user)
            total_price = 0
            for item in cart_items:
                total_price += item.total_price()
            # check if the balance in the wallet is enough to make the purchase
            if total_price <= wallet.balance:
                # get the shipping address for the user
                shipping_address = Address.objects.get(user=request.user)

                # create the Order object
                order = Orderss.objects.create(
                    user=request.user,
                    ordered_date=timezone.now(),
                    shipping_address=shipping_address
                )

                # add the cart items to the order
                order.items.add(*cart_items)
                order.save()

                # set the ordered field to True for the cart items
                for item in cart_items:
                    item.ordered = True
                    item.save()

                # update the balance in the wallet
                wallet.balance -= total_price
                wallet.save()
			
                return redirect('MainClient:cart')
            else:
                messages.warning(request, "Your balance is not enough to make this purchase")
                return redirect('MainClient:cart')
        else:
            messages.warning(request, "You don't have any items in your cart")
            return redirect('MainClient:cart')
    else:
        messages.warning(request, "You must be logged in to create an order")
        return redirect



def cart_view(request):
    cart_items = CartItems.objects.filter(user=request.user, ordered=False)
    total_price = 0
    for cart_item in cart_items:
        total_price += cart_item.item.price * cart_item.quantity
    context = {
        'cart_items': cart_items,
        'total_price': total_price
    }
    return render(request, 'MainClient/cart.html', context)


def welcome(request):
    if request.user.is_authenticated:
        return redirect('customerSide/home')
    else:
        return render(request, 'MainClient/welcome.html')
 
def previous_orders_view(request):
    orders = Orderss.objects.filter(user=request.user)
    context = {
        'orders': []
    }
    for order in orders:
        total_price = 0
        for item in order.items.all():
            total_price += item.total_price()
        context['orders'].append({'order': order, 'total_price': total_price})
    return render(request, 'MainClient/previous_orders.html', context)

def checkout(ItemDetailView):
    pass



def logout_view(request):
    logout(request)
    return redirect('project:welcome')


def thanks(request):
    return render(request, 'thanks.html')

	

project/MainClient/templates/MainClient/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>

header {
    position: relative;
    height: 17vh;
    font-size: xxx-large;
    border-bottom: 0px solid #eee;
    text-align: center;
    background-color: cornflowerblue;
    color: black;
    
  }
  .cart-items {
    display: flex;
    flex-wrap: wrap;
  }
  .cart-item {
    width: 20%;
    display: flex;
    flex-direction: column;
    align-items: center;
    border: solid 4px black;
  }
  .go-back-button {
    position: absolute;
    bottom: 10% ;
    left: 45%;
    transform: translate(-50%, 50%);
    font-size: medium;
  }
  .go-back-profile {
    position: absolute;
    bottom: 10% ;
    left: 55%;
    transform: translate(-50%, 50%);
    font-size: medium;
  }
  .alert{
    font-size: medium;
    color: red;

  }
  
</style>
<header>Your Cart
  <a class="go-back-button" href="{% url 'MainClient:items' %}">
    Go back to items
</a>
<a  class="go-back-profile" href="{% url 'MainClient:customerprofile' user.id %}">
 Profile {{user.username}}
</a>
</header>
<body>
  <h2>Cart</h2>
  <ul class="cart-items">
    
    {% for cart_item in cart_items %}
    
      <li li class="cart-item">
        <img width="150px" height="200px" src="{{ cart_item.item.image.url }}" alt="{{ cart_item.item.title }}">
        <p>{{ cart_item.item.title }}: {{ cart_item.quantity }} x ${{ cart_item.item.price }}</p>
        <form action="{% url 'MainClient:remove_from_cart' cart_item.item.slug %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Remove from cart">
        </form>
      </li>
    {% endfor %}
  </ul><br>
  {% if messages %}
  {% for message in messages %}
    <div class="alert ">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

  <p>Total price: ${{ total_price }}</p>
  

  <form action="{% url 'MainClient:create_order' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Order now">
  </form>
</body>
</html>

project/MainClient/templates/MainClient/customerprofile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: inherit;
        }

        html {
            font-size: 62.5%;
            box-sizing: border-box;
        }

        body {
            color: #eee;
            background-color: #3a1e86;
        }

        /* LAYOUT */
        header {
            position: relative;
            height: 15vh;
            font-size: xxx-large;
            border-bottom: 2px solid #eee;
            text-align: center;
            justify-content: center;
        }

        main {
            height: 65vh;
            color: #eee;
            font-size: xx-large;
            display: flex;
            align-items: center;
            justify-content: space-around;
        }

        fieldset {
            width: 820px;
            height: 500px;
            border-color: rgb(3, 3, 3);
            border-radius: 40px;
            border-width: 2px;
            color: rgb(0, 0, 0);
            display: flex;
            align-items: center;
            background-color: rgb(45, 100, 202);
        }

        strong {
            font-size: xxx-large;
        }

        section {
            margin-left: 20px;
        }
        .cart {
    position: absolute;
    bottom: 15% ;
    left: 90%;
    transform: translate(-50%, 50%);
    font-size: medium;
    color: #eee;
    font-size: xx-large;
    border: solid 2px;
  }

  .itemspage {
    position: absolute;
    bottom: 15% ;
    left: 80%;
    transform: translate(-50%, 50%);
    font-size: medium;
    color: #eee;
    font-size: xx-large;
    border: solid 2px;
  }

    </style>
     {% if user.is_authenticated %}
    <title>Profile Page</title>
</head>

<body>
    <header>
        <h1>{{ user.get_username }}'Profile Page</h1>
        <a class='cart' href="{% url 'MainClient:cart'  %}">Cart</a><br>
        <a class='itemspage' href="{% url 'MainClient:items'  %}">Go back to items</a><br>
    </header>
    
    <main style="float: left; margin-left: 100px;">
        
        <fieldset>
            
            <section>
                <strong>Kullanici ismi:</strong>
                <p>{{ user.get_username }}</p><br>
                <strong>{{user.wallet.name}}</strong>
                <p>the balance {{ user.wallet.balance }} TL</p>
                <strong>Adres</strong>
                <p>{{ user.address.title }}</p>
                <p>{{ user.address.street }}</p>
                
                
                <a href="{% url 'MainClient:walletupdate' user.wallet.slug %}" class="ml-2">edit your wallet</a><br>
                <a href="{% url 'MainClient:addressupdate' user.address.slug %}">edit your address</a>
            </section>
        </fieldset>
    </main>
    <main style="float: right; margin-right: 100px;">
        <fieldset>
            <section>
                
                <strong>the previous orders</strong><br>
                <a href="{% url 'MainClient:previousorder' %}">goes to previous orders</a>
        


            </section>
        </fieldset>
        {%endif%}
    </main>
</body>

</html>

project/MainClient/templates/MainClient/home.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <style>

.loginb {
    background-color: #BFA181;
    color: black;
    border: none;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 70px;
    border-radius: 40px;
    width: 200px;
    height: 65px;
    margin-left: 20px;
    margin-top: 50px;
    transition-duration: 0.4s;
    font-size: 35px;
  }
  .cart {
    position: absolute;
    bottom: 15% ;
    left: 90%;
    transform: translate(-50%, 50%);
    font-size: medium;
    color: rgb(0, 0, 0);
    font-size: xx-large;
    border: solid 5px;
  }
        </style>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <title>Main Page</title>
      </head>
    <body>
        <header>
            <h1 style="text-align: center;">Main Page</h1>
            <a class='cart' href="{% url 'MainClient:cart'  %}">Cart</a><br>
            <form action="{% url 'MainClient:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="loginb">Log out</button>
              </form>
              
            </header>
        <main>
            <section>
                <a href="{% url 'MainClient:items' %}">
                    <button class="item" style="float: right;">Goes to items</button>
                </a>
            </section>
            <section>
                <a href="{% url 'MainClient:customerprofile' user.id %}">
                    <button class="wallet">View profile page</button>
                </a>
            </section>
          </main>
    </body>
</html>

project/MainClient/templates/MainClient/itemdetail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: inherit;
        }

        html {
            font-size: 62.5%;
            box-sizing: border-box;
        }

        body {
            color: #eee;
            background-color: #7545f8;
        }

        /* LAYOUT */
        header {
            position: relative;
            height: 15vh;
            font-size: xxx-large;
            border-bottom: 5px solid #eee;
            text-align: center;
        }

        main {
            height: 65vh;
            color: #eee;
            font-size: x-large;
            display: flex;
            align-items: center;
            justify-content: space-around;
        }

        img {
            align-self: center;
            margin-left: 80px;
        }

        fieldset {
            width: 500px;
            height: 700px;
            border-color: rgb(3, 3, 3);
            border-radius: 40px;
            border-width: 2px;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: rgb(39, 38, 38);
            margin-top: 150px;
        }

        p {
            justify-content: center;
            text-align: center;
        }

        span {
            text-align: center;
            margin-left: 50px;
        }

        button {
            background-color: rgb(244, 246, 250);
            color: rgb(255, 255, 255);
            border: none;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            border-radius: 30px;
            width: 250px;
            margin-top: 10px;
            margin-left: 15px;
            transition-duration: 0.4s;
        }

        button:hover {
            background-color: rgb(102, 151, 243);
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            border-radius: 30px;
            width: 250px;
            margin-left: 15px;
            margin-top: 10px;
        }
    </style>
    <title>Item Details</title>
</head>

<body>
    <header>
        <h1>Item Details</h1>
    </header>
    <main>
        <fieldset>
            <section>
                <p style="font-size: xxx-large;">{{ items.title }}</p>
                <p>      </p><img width="250px" height="250px" src="{{ items.image.url }}" alt="{{ items.title }}"><br>
                <span>{{items.description}}</span><br>
                <p>{{ items.price }}</p><br><br>
                

                <a style="color: white;" href="{% url 'MainClient:add_to_cart' items.slug %}" class="btn btn-primary btn-md my-0 p">
                    Add to cart
                    <i class="fas fa-shopping-cart ml-1"></i>
                  </a>
                     
                  
                
            </section>
        </fieldset>
    </main>
</body>

</html>

project/MainClient/templates/MainClient/itemlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item list page</title>
</head>
<style>
    .item {
        display: inline-block;
        border: solid 4px rgb(141, 14, 14);
        width: 250px;
        height: 320px;
        margin: 10px;
        text-align: center;
        
    }
    header {
    position: relative;
    height: 15vh;
    font-size: xxx-large;
    border-bottom: 5px solid #eee;
    text-align: center;
    background-color: cornflowerblue;
    color: black;
  }
  .go-back-button {
    position: absolute;
    bottom: 10% ;
    left: 45%;
    transform: translate(-50%, 50%);
    font-size: medium;
  }
  .go-back-profile {
    position: absolute;
    bottom: 10% ;
    left: 55%;
    transform: translate(-50%, 50%);
    font-size: medium;
  }
  
</style>
<header>Items
    <a class="go-back-button" href="{% url 'MainClient:cart' %}">
        Cart
    </a>
    <a  class="go-back-profile" href="{% url 'MainClient:customerprofile' user.id %}">
     Profile {{user.username}}
    </a>
</header>
<body>
    
    <div class="grid">
{% for item in object_list %}


<div class='item'>
    <img width="150px" height="200px" src="{{ item.image.url }}" alt="{{ item.title }}">
    <p >{{ item.title }} </p>
    <p>{{ item.price }}TL</p>
    <a href="{% url 'MainClient:itemdetail' item.slug %}">details</a><br>
    <br>
    <form class="d-flex justify-content-left">
        
        
</div>
{% endfor %}
</div>




</body>

</html>

project/MainClient/templates/MainClient/itemupload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title style="color: rgb(187, 57, 57);">Item upload</title>
</head>
<body>
    <form action="{% url 'MainClient:itemupload'  %}" method="POST" class="itemform" name="itemupload">{% csrf_token %}
        <h3>Uploading page form for items</h3>
        <ul class="noBullet">
          <li>
            <label for="title">title</label>
            <input type="text" class="inputFields"  name="title" placeholder="title of the item" value=""  required/>
          </li>
          <li>
            <label for="price">price</label>
            <input type="number" class="inputFields" name="price" placeholder="price" value=""  required/>
          </li>
          <li>
            <label for="description">description</label>
            <input type="text" class="inputFields" name="description" placeholder="description" value=""  required/>
          </li>
          <li>
                <label for="image">image</label>
                <input type='file' class="inputFields" name="image" value=""  required/>

          </li>
           <li id="center-btn">
            <input type="submit" id="submit_btn" name="submit" alt="Join" value="Submit">
          </li>
        </ul>
      </form> 
</body>
</html>

project/MainClient/templates/MainClient/loginform.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/formstyle.css' %}">
        <title>My Wallet</title>
      </head>
      <style>
        label {
    font-size: large;
  }
        input{
          width: 50%;

  }
      </style>
     
    <body>
        <header>
            <h1>My Wallet</h1>
        </header>
        <main>
            <section>
              <fieldset>
                <form action="{% url 'MainClient:loginPage' %}" method="POST" class="form" name="form">{% csrf_token %}
                  <h3>NewLogin</h3>
                  <ul class="noBullet">
                    
                      <label for="username">please enter your user name</label>
                      <input type="text" class="inputFields"  name="username" placeholder="username" value=""  required/>
                    
                      <label for="balance">please enter your password</label>
                      <input type="password" class="inputFields" name="password" placeholder=""  required/>
                    
                   
                    
                    
                     
                    
                      <input type="submit" id="submit_btn" name="submit" alt="Join" value="Submit">
                   
                  </ul>
                </form>
                </fieldset>
            </section>
          </main>
    </body>
</html>

project/MainClient/templates/MainClient/previous_orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Previous orders:</h2>
    <a class="go-back-button" href="{% url 'MainClient:home' %}">
        Home page
    </a>
    
    {% for order_info in orders %}
        <h3>Order placed on {{ order_info.order.ordered_date }}</h3>
        <ul>
            {% for item in order_info.order.items.all %}
                <li>{{ item.item.title }}: {{ item.quantity }} x ${{ item.item.price }}</li>
            {% endfor %}
        </ul>
        <p>Total price: ${{ order_info.total_price }}</p>
    {% endfor %}
    

</body>
</html>

project/MainClient/templates/MainClient/welcome.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <title>Main Page</title>
      </head>
    <body>
        <header>
            <h1 style="text-align: center;">Welcome</h1>
            
        </header>
        <main>
            <section>
                <a href="{% url 'MainClient:loginPage' %}">
                    <button class="item" style="float: right;">Please login here</button>
                </a>
            </section>
            <section>
                
                <a href="{% url 'MainClient:register.new' %}">
                    <button class="wallet">Registration</button>
                    <p>If you dont have an account you can register from here</p>
                </a>
            </section>
          </main>
    </body>
</html>